version: '3'

services:

  client:
    build:
      context: ./off-by
      dockerfile: Dockerfile
    image: myapp-client
    command: npm start
    volumes:
      - ./off-by/src:/usr/app/src
    depends_on:
      - server
    ports:
      - 3000:3000

    networks:
      - app-network
    environment:
      - REACT_APP_SERVER=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

    links:
      - "server:be"

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/usr/app/src
    ports:
      - "5000:5000"
    depends_on:
      - my-db
    environment:
      - MYSQL_HOST_IP= 'my-db'
      - DB_HOST='my-db'
      - DB_USER='admin'
      - DB_PASSWORD='otters'
      - DB_NAME='obdb'
      - DB_PORT='3306'
      
    networks:
      - app-network

  my-db:
    image: mysql/mysql-server
    restart: always
    command: --default-authentication-plugin=mysql_native_password --local-infile=ON
    environment:
      MYSQL_DATABASE: obdb
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'otters'
      MYSQL_ROOT_PASSWORD: 'otters'
      MYSQL_HOST: localhost

    volumes:
      - data-volume:/data/db
    ports:
      - '3306:3306'
    networks:
      - app-network
    expose:
      # Opens port 3306 on the container
      - '3306'

networks: 
  app-network:
    driver: bridge
  
volumes: 
    data-volume:
    node_modules:
    web-root:
      driver: local
